blocos= { "0000":["0000","COD_VER","COD_FIN","DT_INI","DT_FIN","NOME","CNPJ","CPF","UF","IE","COD_MUN","IM","SUFRAMA","IND_PERFIL","IND_ATIV",],
"0001":["0001","IND_MOV",],
"0005":["0005","FANTASIA","CEP","END","NUM","COMPL","BAIRRO","FONE","FAX","EMAIL",],
"0100":["0100","NOME","CPF","CRC","CNPJ","CEP","END","NUM","COMPL","BAIRRO","FONE","FAX","EMAIL","COD_MUN",],
"0150":["0150 - Fixo","Código Participante","Razão Social","Código País","CNPJ do Participante","CPF do Participante","Inscrição Estadual","Código Municipio","Suframa","Endereço","Número","Complemento","Bairro",],
"0190":["0190 - Fixo","Unidade de Medida","Descrição da Unidade de Medida",],
"0200":["0200 - Fixo","Código do Produto/Serviços","Descrição do Produto/Serviços","Código de Barras","Código Anterior","Unidade de Medida","Tipo de Item","NCM","EX_IPI","Código do Genero","Código Lista de Serviçs","Aliquota de ICMS","CEST",],
"0400":["0400 - Fixo","Código da Natureza de Operação","Descrição da Natureza de Operação",],
"0450":["0450","COD_INF","TXT",],
"0990":["0990","QTD_LIN_0",],
"B001":["B001","IND_DAD",],
"B990":["B990","QTD_LIN_B",],
"C001":["C001","IND_MOV",],
"C100":["C100 - Fixo","Indicador de Operação","Indicador de Emissão","Participante","Modelo","Situação","Série","Número","Chave","Data de Emissão","Data de Entrada/Saída","Valor","Pagamento","Desconto","Abatimento","Valor das Mercadorias","Tipo de Frete","Valor do Frete","Valor do Seguro","Despesas Acessróias","BC de ICMS","Valor de ICMS","BC de ICMS ST","Valor de ICMS - ST","Valor de IPI","Valor de Pis","Valor de Cofins","Valor de Pis - ST","Valor de Cofins - ST",],
"C110":["Participante(C100)","Número da Nota(C100)","Modelo(C100)","Série(C100)","C110","COD_INF","TXT_COMPL",],
"C170":["Participante(C100)","Número da Nota(C100)","Modelo(C100)","Série(C100)","Chave de Acesso(C100)","C170 - Fixo","Numeraçã£o Sequencial","Código do Produto","DescriÃ§Ã£o Complementar","Quantidade","Unidade de Medida","Valor Total do Produto","Valor de Desconto","Movimentação Física","CST de ICMS","CFOP","Natureza de Operação","Base de Icms","Alíquota de Icms","Valor de Icms","Base de Icms ST","Alíquota de Icms ST","Valor de Icms ST","Indicador de Apuração de IPI","CST de IPI","Código Enquadramento IPI","Base de IPI","Alíquota de IPI","Valor de IPI","CST de Pis","Base de Pis","Alíquota de Pis","Base de Pis - Qtde","AlÃ­quota de Pis Qtde","Valor de Pis","CST de Cofins","Base de Cofins","Alíquota de Cofins","Base de Cofins - Qtde","Alíquota de Cofins Qtde","Valor de Cofins","Conta Contábil","Valor do abatimento não tributado",],
"C190":["Participante(C100)","Número da Nota(C100)","Modelo(C100)","Série(C100)","C190 - Fixo","CST de ICMS","CFOP","Alíquota de Icms","Valor da Operação","Base de Icms","Valor de Icms","Base de Icms ST","Valor de Icms ST","Valor Redução de Base de Icms","Valor de IPI","Código de Observações",],
"C800":["C800 - Fixo","Modelo","Situação","Número","Data de Emissão","Valor","Valor de Pis","Valor de Cofins","CPF ou CNPJ do Participante","Numero do SAT","Chave","Desconto","Valor das Mercadorias","Valor do Desp. Acessórias","Valor de ICMS","Valor de Pis - ST","Valor de Cofins - ST",],
"C850":["Número do Cupom Eletrônico(C800)","Numero do SAT(C800)","C850 - Fixo","CST de ICMS","CFOP","Alíquota de Icms","Valorda Operação","Base de Icms","Valor de Icms","Código de Observações",],
"C990":["C990","QTD_LIN_C",],
"D001":["D001","IND_MOV",],
"D990":["D990","QTD_LIN_D",],
"E001":["E001","IND_MOV",],
"E100":["E100","DT_INI","DT_FIN",],
"E110":["DT_INI(E100)","DT_FIN(E100)","E110","VL_TOT_DEBITOS","VL_AJ_DEBITOS","VL_TOT_AJ_DEBITOS","VL_ESTORNOS_CRED","VL_TOT_CREDITOS","VL_AJ_CREDITOS","VL_TOT_AJ_CREDITOS","VL_ESTORNOS_DEB","VL_SLD_CREDOR_ANT","VL_SLD_APURADO","VL_TOT_DED","VL_ICMS_RECOLHER","VL_SLD_CREDOR_TRANSPORTAR","DEB_ESP",],
"E990":["E990","QTD_LIN_E",],
"G001":["G001","IND_MOV",],
"G990":["G990","QTD_LIN_G",],
"H001":["H001","IND_MOV",],
"H005":["H005","DT_INV","VL_INV","MOT_INV",],
"H990":["H990","QTD_LIN_H",],
"K001":["K001","IND_MOV",],
"K990":["K990","QTD_LIN_K",],
"1001":["1001","IND_MOV",],
"1010":["1010","IND_EXP","IND_CCRF","IND_COMB","IND_USINA","IND_VA","IND_EE","IND_CART","IND_FORM","IND_AER","IND_GIAF1","IND_GIAF3","IND_GIAF4","IND_REST_RESSARC_COMPL_ICMS",],
"1990":["1990","QTD_LIN_1",],
"9001":["9001","IND_MOV",],
"9900":["9900","REG_BLC","QTD_REG_BLC",],
"9990":["9990","QTD_LIN_9",],
"9999":["9999","QTD_LIN",]}